Repository ampache/ampache, pull requests merged in 2021-03, with the labels that each got.

#2782 Correct user count calculation
  lib/class/api.class.php
Labels: bug

#2809 Allow the object id to be used as a list of ids
  resources/templates/playlist/new_dialog.xhtml
  src/Gui/GuiFactory.php
  src/Gui/GuiFactoryInterface.php
  src/Gui/Playlist/NewPlaylistDialogAdapter.php
  src/Gui/Playlist/NewPlaylistDialogAdapterInterface.php
  src/Module/Api/Edit/ShowEditPlaylistAction.php
  tests/Gui/GuiFactoryTest.php
  tests/Gui/Playlist/NewPlaylistDialogAdapterTest.php
Labels: bug

#2836 Two CSS files for jquery dialogs weren't being found.
  public/templates/header.inc.php
  public/templates/stylesheets.inc.php
Labels: UI, bug

#2831 Give correct MetadataField in Ampache\Repository\Model\Metadata\Model\Metadata
  src/Repository/Model/Metadata/Metadata.php
  src/Repository/Model/Metadata/Model/Metadata.php
Labels: bug

#2827 Extend Ziphandler add abilility to add art and m3u
  config/ampache.cfg.php.dist
  src/Config/ConfigurationKeyEnum.php
  src/Config/Init/InitializationHandlerConfig.php
  src/Module/Util/ZipHandler.php
Labels: enhancement
