Repository ampache/ampache, pull requests merged in 2021-02, with the labels that each got.

#2717 Indicate currently active sidebar tab
  public/themes/reborn/templates/default.css
Labels: enhancement

#2718 Use outline for album art hover
  public/themes/reborn/templates/dark.css
  public/themes/reborn/templates/default.css
  public/themes/reborn/templates/light.css
Labels: enhancement

#2738 Add missing parameter for Upnp_Api::createDIDL call
  modules/localplay/upnp/upnpplayer.class.php
Labels: bug

#2739 Stop logging auth/passphrase strings
  graph.php
  image.php
  lib/class/ApiMethods/GoodbyeMethod.php
  lib/class/ApiMethods/HandshakeMethod.php
  lib/class/ApiMethods/PingMethod.php
  server/xml.server.php
Labels: security

#2747 Correct parameter name
  lib/class/catalog.class.php
Labels: bug

#2722 Drop deprecated api methods
  src/Module/Api/Api.php
  src/Module/Api/Method/TagAlbumsMethod.php
  src/Module/Api/Method/TagArtistsMethod.php
  src/Module/Api/Method/TagMethod.php
  src/Module/Api/Method/TagSongsMethod.php
  src/Module/Api/Method/TagsMethod.php
Labels: Deprecated, api, testing

#2700 Added favorite feature for songs
  client/Contexts/MusicContext.tsx
  client/Views/App.tsx
  client/components/MusicControl.tsx
  client/components/Rating/index.tsx
  client/components/SongRow/index.tsx
Labels: react-client
